---
title: "MODFLOW_impact_table"
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{MODFLOW_impact_table}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
library(CSLSscenarios)
library(dplyr)
library(reshape2)
library(DT)
library(shiny)

MODFLOW_comparison <- CSLSscenarios::MODFLOW_comparison

round_value <- function(val, metric) {
  # Reference
  digits2 <- c("exceedance_level", "exceedance_range", "solute_budget")
  digits1 <- c("stratification", "turtle_bay", "is_lake", "motorboat", 
               "dock", "good_spawning")
  digits0 <- c("num_2yr")
  
  val <- as.numeric(val)
  
  # Evaluate
  if (metric %in% digits2) {
    rounded <- round(val,2)
  } else if (metric %in% digits1) {
    rounded <- round(val,1)
  } else if (metric %in% digits0) {
    rounded <- round(val,0)
  } else {
    warning("metric not known, add to list")
  }
  
  return(rounded)
}


for (i in 1:nrow(MODFLOW_comparison)) {
  for (col_name in c("value1", "value2", "threshold", "threshold_diff", 
                     "diff", "bathy1", "bathy_threshold", "bathy2", 
                     "bathy_threshold_diff", "bathy_diff")) {
    MODFLOW_comparison[i,col_name] <- round_value(MODFLOW_comparison[i,col_name],
                                         MODFLOW_comparison$metric[i])
  }
}
```

```{r eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
# Most limiting by ecological category -----------------------------------------
limiting      <- MODFLOW_comparison %>%
                 group_by(.data$sim_type,
                          .data$lake,
                          .data$hydrology,
                          .data$metric,
                          .data$variable,
                          .data$value1,
                          .data$value2,
                          .data$diff,
                          .data$category,
                          .data$significant_if) %>%
                 mutate(limit_threshold = ifelse(.data$significant_if == "lower",
                                                 max(.data$threshold, na.rm = TRUE),
                                                 min(.data$threshold, na.rm = TRUE))) %>%
                 filter(.data$limit_threshold == .data$threshold) %>%
                 ungroup() %>%
                 select(.data$sim_type,
                        .data$lake,
                        .data$hydrology,
                        .data$metric,
                        .data$variable,
                        .data$category,
                        .data$indicator,
                        .data$impacted,
                        .data$significant_if,
                        .data$value1,
                        .data$threshold,
                        .data$value2,
                        .data$threshold_diff,
                        .data$diff,
                        .data$bathy_significant_if,
                        .data$bathy1,
                        .data$bathy_threshold,
                        .data$bathy2,
                        .data$bathy_threshold_diff,
                        .data$bathy_diff)

# Most limiting by hydrologic metric -------------------------------------------
most_limiting <- MODFLOW_comparison %>%
                 group_by(.data$sim_type,
                          .data$lake,
                          .data$hydrology,
                          .data$metric,
                          .data$variable,
                          .data$value1,
                          .data$value2,
                          .data$diff,
                          .data$significant_if) %>%
                 mutate(limit_threshold = ifelse(.data$significant_if == "lower",
                                                 max(.data$threshold, na.rm = TRUE),
                                                 min(.data$threshold, na.rm = TRUE))) %>%
                 filter(.data$limit_threshold == .data$threshold) %>%
                 ungroup() %>%
                 select(.data$sim_type,
                        .data$lake,
                        .data$hydrology,
                        .data$metric,
                        .data$variable,
                        .data$category,
                        .data$indicator,
                        .data$impacted,
                        .data$significant_if,
                        .data$value1,
                        .data$threshold,
                        .data$value2,
                        .data$threshold_diff,
                        .data$diff,
                        .data$bathy_significant_if,
                        .data$bathy1,
                        .data$bathy_threshold,
                        .data$bathy2,
                        .data$bathy_threshold_diff,
                        .data$bathy_diff)

```

```{r eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
# Friendly names

sim_type  <- data.frame(value = c("conservative", "base", "permissive"),
                        label = c("High-Impact", "Base", "Low-Impact"))
hydrology <- data.frame(value = c("magnitude", "frequency", "duration",
                                     "rate_of_change", "timing", "fluxes"),
                        label = c("Magnitude", "Frequency", "Duration",
                                     "Rate of Change", "Timing", "Fluxes"))
metric    <- data.frame(value = c("exceedance_level", "exceedance_range",
                                  "turtle_bay", "stratification", "dock",
                                  "motorboat", "paddleboat", "num_2yr", 
                                  "good_spawning", "solute_budget"),
                        label = c("Exceedance Level", "Exceedance Range",
                                  "Turtle Bay", "Stratification", "Docks",
                                  "Motorboating", "Paddle Sports", 
                                  "2+ yr Durations", "Pike Spawning", 
                                  "Solute Budget"))
variable  <- data.frame(value = c("10", "25", "50", "75", "90", "range_10_90",
                                  "a50", "b50", "percent_connect_warm", 
                                  "percent_strat", "percent_install", 
                                  "percent_good_year", "percent_no_move",
                                  "percent_ok", "good_spawning", "median",
                                  "max"),
                        label = c("Infrequent High", "Frequent High",
                                  "Median", "Frequent Low", "Infrequent Low",
                                  "Range High - Low", "Above Median", 
                                  "Below Median", "% Years Connected",
                                  "% Time Stratified", "% Years Installed", 
                                  "% Years Not Moved", "% Years Good",
                                  "% Time Possible", "% Years Good", "Median",
                                  "Maximum"))
category <- data.frame(value = c("chemistry", "plants", "fish", "human_use"),
                       label = c("Chemistry", "Plants", "Fish", "Human Use"))
indicator <- data.frame(value = c("volume_habitat", "area_habitat", 
                                  "littoral_habitat", "upland", "inland_beach",
                                  "emergent", "floating", "submergent",
                                  "submergent_algae", "submergent_weed",
                                  "threatened_plant", "motorboat_crowding",
                                  "range_decrease", "range_increase", 
                                  "high_levels", "low_levels", "stratification",
                                  "turtle_bay", "motorboat", "paddleboat",
                                  "install_dock", "good_dock", "no_move_dock",
                                  "good_spawning", "low_solute_median", 
                                  "high_solute_median", "solute_max"),
                        label = c("Physical Habitat (Volume)", 
                                  "Physical Habitat (Area)", 
                                  "Littoral Habitat (Substrate)", 
                                  "Upland", "Inland Beach", "Emergents", 
                                  "Floating-Leaf", "Submergents", 
                                  "Submergents (Macroalgae)", 
                                  "Submergents (Pondweed)",
                                  "Federally-Listed Threatened", 
                                  "Motorboat Crowding", 
                                  "Range (Decrease)", 
                                  "Range (Increase)", 
                                  "Prolonged High Levels", 
                                  "Prolonged Low Levels", 
                                  "Stratification", 
                                  "Turtle Bay Connection", 
                                  "Motorboats Possible", 
                                  "Paddle Sports Possible", 
                                  "Install Dock", "Good Dock", "No Move Dock", 
                                  "Pike Spawning",
                                  "Median Mg (Decrease)",
                                  "Median Mg (Increase)",
                                  "Maximum Mg"))
significant_if <- data.frame(value = c("higher", "lower"),
                       label = c("Higher", "Lower"))
```

```{r eval=FALSE, echo=FALSE, warning=FALSE, message=FALSE}
limiting <- limiting %>%
            mutate_at(c("sim_type", "hydrology", "metric", "variable", 
                        "category", "indicator", "significant_if"),
                      as.factor)

limiting$sim_type <- factor(limiting$sim_type, 
                            levels = sim_type$value, 
                            labels = sim_type$label)
limiting$hydrology <- factor(limiting$hydrology, 
                            levels = hydrology$value, 
                            labels = hydrology$label)
limiting$metric <- factor(limiting$metric, 
                            levels = metric$value, 
                            labels = metric$label)
limiting$variable <- factor(limiting$variable, 
                            levels = variable$value, 
                            labels = variable$label)
limiting$category <- factor(limiting$category, 
                            levels = category$value, 
                            labels = category$label)
limiting$indicator <- factor(limiting$indicator, 
                            levels = indicator$value, 
                            labels = indicator$label)
limiting$significant_if <- factor(limiting$significant_if, 
                            levels = significant_if$value, 
                            labels = significant_if$label)

colnames(limiting) <- c("Run", "Lake", "Hydrology", "Metric", "Variable",
                       "Category", "Indicator", "Impacted?", "Significant If",
                       "No Irrigation", "Threshold", "Current Irrigation", 
                       "Threshold Difference", "Difference", 
                       "Bathymetry Significant If", "Bathymetry No Irrigation",
                       "Bathymetry Threshold", "Bathymetry Current Irrigation",
                       "Bathymetry Threshold Difference", 
                       "Bathymetry Difference")
# datatable(limiting, filter = 'top')

runApp(list(
  ui = basicPage(
    checkboxGroupInput("select", "Select columns to display", colnames(limiting)),
    h2('Limiting Ecological Indicators'),
    dataTableOutput('mytable')
  ),
  server = function(input, output) {
    output$mytable = renderDataTable({
      columns = names(limiting)
      if (!is.null(input$select)) {
        columns = input$select
      }
      limiting[,columns,drop=FALSE]
    })
  }
))
```
