---
title: "MODFLOW_differences"
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{MODFLOW_differences}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
library(CSLSscenarios)
library(dplyr)
library(reshape2)
library(NISTunits)
library(lubridate)
library(ggplot2)
library(extrafont)
library(DT)

scenarios <- data.frame(scenario = c("no_irr", "cur_irr", "fut_irr"),
                        scenario_name = c("No Irrigation", 
                                          "Current Irrigation",
                                          "Future Irrigation"),
                        colors = c("steelblue4", "goldenrod1", "darkorange"))

# Lake Levels ------------------------------------------------------------------
MODFLOW <- CSLSdata::MODFLOW %>%
           filter(.data$scenario %in% scenarios$scenario,
                  year(.data$date) >= 1986,
                  year(.data$date) <= 2018,
                  .data$sim %in% c(1, 196, 277)) %>%
           mutate(year = year(.data$date),
                  month = month(.data$date),
                  time = .data$year - min(.data$year) + .data$month/12,
                  level = NISTmeterTOft(.data$level_m)) %>%
           left_join(scenarios, by = "scenario") %>%
           select(scenario = .data$scenario_name,
                  sim = .data$sim,
                  lake = .data$lake, 
                  date = .data$date,
                  time = .data$time,
                  level = .data$level)
df1 <- MODFLOW %>% filter(.data$scenario == "No Irrigation")
df2 <- MODFLOW %>% filter(.data$scenario == "Current Irrigation")
compare <- full_join(df1, df2, by = c("lake", "sim", "date", "time"))
compare$diff <- compare$level.y - compare$level.x

```

```{r eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}



```

